# Write your solution here
g_Name = input("Given name: ")
f_name = input("Family name: ")
s_Address = input("Street address: ")
c_code = input("City and postal code: ")
#print("Given name: " + g_Name)
#print("Family name: " + f_name)
#print("Street address: " + s_Address)
#print("City amd postal code: " + c_code)
print(g_Name + " " + f_name)
print(s_Address)
print(c_code)